name: CFN Specification and User Guide Audit

on: #push
 schedule: 
  - cron: 0 */12 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git submodule update --init --recursive --remote
        python -m pip install --upgrade pip setuptools
        pip install pipenv
        pipenv install --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Look for and update new CFN specs if found
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        git checkout master
        pipenv run python tools/cfn-resource-list.py
    - name: Audit documentation links and cfn user guide
      run: |
        cp supported-regions-per-resource.json supported-regions-per-resource-old.json
        pipenv run python tools/cfn-supported-region-generator.py
    - name: Generate changelog source
      run: |
        pipenv run python tools/cfn-changelogger.py
    - name: Generate changelog markdown
      run: |
        pipenv run python tools/create-changelog.py
    - name: Create pull request if any files were updated
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_PR_TOKEN }}
        labels: automerge
    - name: Check outputs and automerge if PR was made
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_PR_TOKEN }}
      run: |
        PR_NUMBER=${{ steps.cpr.outputs.pull-request-number }}
        echo "Pull Request Number - $PR_NUMBER"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

        # Attempt automerge if PR was made
        if [[ -n $PR_NUMBER ]]; then
          gh pr merge $PR_NUMBER -m -d -s
        fi
